######################## default configuration ####################
baseURL = "https://meducationx.github.io/"
title = "Meducation | Get Meducated"
theme = "gojournal"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "20"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

#[[menu.main]]
#name = "Privacy Policy"
#URL = "privacy-policy"
#weight = 2

#[[menu.main]]
#name = "More Hugo Theme"
#URL = "https://gethugothemes.com/shop/"
#weight = 2
  
[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.main]]
name = "Quizzes"
url = "quizzes"
weight = 5

[[menu.main]]
name = "Competitions"
URL = "competitions"
weight = 6

[[menu.main]]
name = "Links"
URL = "https://meducationx.carrd.co"
weight = 10

# footer menu

[[menu.footer]]
name = "contact"
URL = "contact"
weight = 1


#[[menu.footer]]
#name = "privacy policy"
#URL = "privacy-policy"
#weight = 2

#################### default parameters ################################
[params]
logo = "images/BLUELOGOONLY.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "https://docs.google.com/forms/d/e/1FAIpQLSd73iLUo4NsczzaTV6GwUtVEzif-1Cvn3UZIOf53UAREvAngg/formResponse" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# sidebar
sidebar = "left" #sidebar value (left,right,false)
copyright = "Copyright &copy; 2023 [MeducationX](https://meducationx.github.io/)"

# Preloader
[params.preloader]
enable = true
preloader = "images/BLUELOGOONLY.png" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# promotion 
[params.promotion]
enable = false
image = "images/promotion.png"
link = "#"

# Instagram feed
[params.instafeed]
enable = true
user_id = "6948265175253817"
access_token = ""
  
############################# social site ########################
#[[params.social]]
#title = "facebook"
#icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "twitter"
#icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://instagram.com/meducationx"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/meducationx"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# subscription
subscription_title = "Join MeducationX for the latest news"
subscription_content = "Subscribe now to get notified about exclusive News And Views Issues every week!"
# copyright
copyright = "Copyright &copy; 2023 [MeducationX](https://meducation.github.io/)"


################################### French language #####################################
#[Languages.fr]
#languageName = "Fr"
#languageCode = "fr-fr"
#contentDir = "content/french"
#weight = 2
#home = "Accueil"
# subscription
#subscription_title = "Rejoignez Newteller pour les derni√®res nouvelles"
#subscription_content = "Subscribe now to get notified about exclusive News And Views Issues every week!"
# copyright
#copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"